#!/usr/bin/perl
use strict;
use warnings;
use IO::Socket;
use POSIX;
use MIME::Base64;
use Encode;
use encoding 'utf8';
use POSIX qw(strftime);
use Sys::Hostname;
$| = 1;
my @mail_contents = (
'<html><head><title>电商第二平台我友商城为您带来元宵节的祝福</title><meta http-equiv="Content-Type" content="text/html; charset=gb2312"></head><body bgcolor="#FFFFFF" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0"><!-- ImageReady Slices (B1.jpg) --><table id="Table_01" width="750" height="600" border="0" cellpadding="0" cellspacing="0" align="center"><tr><td colspan="3"><img src="http://static.woyo.com/woyo/m110214/images/B1_01.jpg" width="750" height="131" alt=""></td></tr><tr><td colspan="3"><img src="http://static.woyo.com/woyo/m110214/images/B1_02.jpg" width="750" height="101" alt=""></td></tr><tr><td colspan="3"><img src="http://static.woyo.com/woyo/m110214/images/B1_03.jpg" width="750" height="117" alt=""></td></tr><tr><td colspan="3"><img src="http://static.woyo.com/woyo/m110214/images/B1_04.jpg" width="750" height="143" alt=""></td></tr><tr><td rowspan="2"><img src="http://static.woyo.com/woyo/m110214/images/B1_05.jpg" width="327" height="108" alt=""></td><td><a href="http://www.woyo.com/about/business_cooperation/" target="_blank"><img src="http://static.woyo.com/woyo/m110214/images/B1_06.jpg" width="121" height="41" alt="" border="0"></a></td><td rowspan="2"><img src="http://static.woyo.com/woyo/m110214/images/B1_07.jpg" width="302" height="108" alt=""></td></tr><tr><td><img src="http://static.woyo.com/woyo/m110214/images/B1_08.jpg" width="121" height="67" alt=""></td></tr></table><!-- End ImageReady Slices --></body></html>',
'<html><head><title>电商第二平台我友商城为您带来元宵节的祝福</title><meta http-equiv="Content-Type" content="text/html; charset=gb2312"></head><body bgcolor="#FFFFFF" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0"><!-- ImageReady Slices (B2.jpg) --><table id="Table_01" width="750" height="600" border="0" cellpadding="0" cellspacing="0" align="center"><tr><td colspan="3"><img src="http://static.woyo.com/woyo/m110214/images/B2_01.jpg" width="750" height="97" alt=""></td></tr><tr><td colspan="3"><img src="http://static.woyo.com/woyo/m110214/images/B2_02.jpg" width="750" height="100" alt=""></td></tr><tr><td colspan="3"><img src="http://static.woyo.com/woyo/m110214/images/B2_03.jpg" width="750" height="98" alt=""></td></tr><tr><td colspan="3"><img src="http://static.woyo.com/woyo/m110214/images/B2_04.jpg" width="750" height="102" alt=""></td></tr><tr><td colspan="3"><img src="http://static.woyo.com/woyo/m110214/images/B2_05.jpg" width="750" height="95" alt=""></td></tr><tr><td><img src="http://static.woyo.com/woyo/m110214/images/B2_06.jpg" width="38" height="46" alt=""></td><td><a href="http://www.woyo.com/about/business_cooperation/" target="_blank"><img src="http://static.woyo.com/woyo/m110214/images/B2_07.jpg" width="120" height="46" alt="" border="0"></a></td><td rowspan="2"><img src="http://static.woyo.com/woyo/m110214/images/B2_08.jpg" width="592" height="108" alt=""></td></tr><tr><td colspan="2"><img src="http://static.woyo.com/woyo/m110214/images/B2_09.jpg" width="158" height="62" alt=""></td></tr></table><!-- End ImageReady Slices --></body></html>',
'<html><head><title>电商第二平台我友商城为您带来元宵节的祝福</title><meta http-equiv="Content-Type" content="text/html; charset=gb2312"></head><body bgcolor="#FFFFFF" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0"><!-- ImageReady Slices (B3.jpg) --><table id="Table_01" width="750" height="600" border="0" cellpadding="0" cellspacing="0" align="center"><tr><td colspan="3"><img src="http://static.woyo.com/woyo/m110214/images/B3_01.jpg" width="750" height="95" alt=""></td></tr><tr><td colspan="3"><img src="http://static.woyo.com/woyo/m110214/images/B3_02.jpg" width="750" height="105" alt=""></td></tr><tr><td colspan="3"><img src="http://static.woyo.com/woyo/m110214/images/B3_03.jpg" width="750" height="92" alt=""></td></tr><tr><td colspan="3"><img src="http://static.woyo.com/woyo/m110214/images/B3_04.jpg" width="750" height="109" alt=""></td></tr><tr><td colspan="3"><img src="http://static.woyo.com/woyo/m110214/images/B3_05.jpg" width="750" height="108" alt=""></td></tr><tr><td rowspan="2"><img src="http://static.woyo.com/woyo/m110214/images/B3_06.jpg" width="35" height="91" alt=""></td><td><a href="http://www.woyo.com/about/business_cooperation/" target="_blank"><img src="http://static.woyo.com/woyo/m110214/images/B3_07.jpg" width="122" height="46" alt="" border="0"></a></td><td rowspan="2"><img src="http://static.woyo.com/woyo/m110214/images/B3_08.jpg" width="593" height="91" alt=""></td></tr><tr><td><img src="http://static.woyo.com/woyo/m110214/images/B3_09.jpg" width="122" height="45" alt=""></td></tr></table><!-- End ImageReady Slices --></body></html>',
'<html><head><title>电商第二平台我友商城为您带来元宵节的祝福</title><meta http-equiv="Content-Type" content="text/html; charset=gb2312"></head><body bgcolor="#FFFFFF" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0"><!-- ImageReady Slices (B4.jpg) --><table id="Table_01" width="700" height="650" border="0" cellpadding="0" cellspacing="0" align="center"><tr><td colspan="3"><img src="http://static.woyo.com/woyo/m110214/images/B4_01.jpg" width="700" height="136" alt=""></td></tr><tr><td colspan="3"><img src="http://static.woyo.com/woyo/m110214/images/B4_02.jpg" width="700" height="110" alt=""></td></tr><tr><td colspan="3"><img src="http://static.woyo.com/woyo/m110214/images/B4_03.jpg" width="700" height="146" alt=""></td></tr><tr><td colspan="3"><img src="http://static.woyo.com/woyo/m110214/images/B4_04.jpg" width="700" height="189" alt=""></td></tr><tr><td rowspan="2"><img src="http://static.woyo.com/woyo/m110214/images/B4_05.jpg" width="303" height="69" alt=""></td><td><a href="http://www.woyo.com/about/business_cooperation/" target="_blank"><img src="http://static.woyo.com/woyo/m110214/images/B4_06.jpg" width="133" height="55" alt="" border="0"></a></td><td rowspan="2"><img src="http://static.woyo.com/woyo/m110214/images/B4_07.jpg" width="264" height="69" alt=""></td></tr><tr><td><img src="http://static.woyo.com/woyo/m110214/images/B4_08.jpg" width="133" height="14" alt=""></td></tr></table><!-- End ImageReady Slices --></body></html>',
'<html><head><title>电商第二平台我友商城为您带来元宵节的祝福</title><meta http-equiv="Content-Type" content="text/html; charset=gb2312"></head><body bgcolor="#FFFFFF" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0"><!-- ImageReady Slices (B5.jpg) --><table id="Table_01" width="700" height="650" border="0" cellpadding="0" cellspacing="0" align="center"><tr><td colspan="3"><img src="http://static.woyo.com/woyo/m110214/images/B5_01.jpg" width="700" height="134" alt=""></td></tr><tr><td colspan="3"><img src="http://static.woyo.com/woyo/m110214/images/B5_02.jpg" width="700" height="121" alt=""></td></tr><tr><td colspan="3"><img src="http://static.woyo.com/woyo/m110214/images/B5_03.jpg" width="700" height="144" alt=""></td></tr><tr><td colspan="3"><img src="http://static.woyo.com/woyo/m110214/images/B5_04.jpg" width="700" height="131" alt=""></td></tr><tr><td rowspan="2"><img src="http://static.woyo.com/woyo/m110214/images/B5_05.jpg" width="221" height="120" alt=""></td><td><a href="http://www.woyo.com/about/business_cooperation/" target="_blank"><img src="http://static.woyo.com/woyo/m110214/images/B5_06.jpg" width="131" height="56" alt="" border="0"></a></td><td rowspan="2"><img src="http://static.woyo.com/woyo/m110214/images/B5_07.jpg" width="348" height="120" alt=""></td></tr><tr><td><img src="http://static.woyo.com/woyo/m110214/images/B5_08.jpg" width="131" height="64" alt=""></td></tr></table><!-- End ImageReady Slices --></body></html>',
'<html><head><title>电商第二平台我友商城为您带来元宵节的祝福</title><meta http-equiv="Content-Type" content="text/html; charset=gb2312"></head><body bgcolor="#FFFFFF" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0"><!-- ImageReady Slices (B6.jpg) --><table id="Table_01" width="700" height="650" border="0" cellpadding="0" cellspacing="0" align="center"><tr><td colspan="3"><img src="http://static.woyo.com/woyo/m110214/images/B6_01.jpg" width="700" height="160" alt=""></td></tr><tr><td colspan="3"><img src="http://static.woyo.com/woyo/m110214/images/B6_02.jpg" width="700" height="152" alt=""></td></tr><tr><td colspan="3"><img src="http://static.woyo.com/woyo/m110214/images/B6_03.jpg" width="700" height="147" alt=""></td></tr><tr><td rowspan="2"><img src="http://static.woyo.com/woyo/m110214/images/B6_04.jpg" width="67" height="191" alt=""></td><td><a href="http://www.woyo.com/about/business_cooperation/" target="_blank"><img src="http://static.woyo.com/woyo/m110214/images/B6_05.jpg" width="135" height="63" alt="" border="0"></a></td><td rowspan="2"><img src="http://static.woyo.com/woyo/m110214/images/B6_06.jpg" width="498" height="191" alt=""></td></tr><tr><td><img src="http://static.woyo.com/woyo/m110214/images/B6_07.jpg" width="135" height="128" alt=""></td></tr></table><!-- End ImageReady Slices --></body></html>',
'<html><head><title>电商第二平台我友商城为您带来元宵节的祝福</title><meta http-equiv="Content-Type" content="text/html; charset=gb2312"></head><body bgcolor="#FFFFFF" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0"><!-- ImageReady Slices (B7.jpg) --><table id="Table_01" width="750" height="600" border="0" cellpadding="0" cellspacing="0" align="center"><tr><td colspan="3"><img src="http://static.woyo.com/woyo/m110214/images/B7_01.jpg" width="750" height="161" alt=""></td></tr><tr><td colspan="3"><img src="http://static.woyo.com/woyo/m110214/images/B7_02.jpg" width="750" height="96" alt=""></td></tr><tr><td colspan="3"><img src="http://static.woyo.com/woyo/m110214/images/B7_03.jpg" width="750" height="108" alt=""></td></tr><tr><td colspan="3"><img src="http://static.woyo.com/woyo/m110214/images/B7_04.jpg" width="750" height="127" alt=""></td></tr><tr><td rowspan="2"><img src="http://static.woyo.com/woyo/m110214/images/B7_05.jpg" width="65" height="108" alt=""></td><td><a href="http://www.woyo.com/about/business_cooperation/" target="_blank"><img src="http://static.woyo.com/woyo/m110214/images/B7_06.jpg" width="86" height="93" alt="" border="0"></a></td><td rowspan="2"><img src="http://static.woyo.com/woyo/m110214/images/B7_07.jpg" width="599" height="108" alt=""></td></tr><tr><td><img src="http://static.woyo.com/woyo/m110214/images/B7_08.jpg" width="86" height="15" alt=""></td></tr></table><!-- End ImageReady Slices --></body></html>',
'<html><head><title>电商第二平台我友商城为您带来元宵节的祝福</title><meta http-equiv="Content-Type" content="text/html; charset=gb2312"></head><body bgcolor="#FFFFFF" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0"><!-- ImageReady Slices (B8.jpg) --><table id="Table_01" width="750" height="600" border="0" cellpadding="0" cellspacing="0" align="center"><tr><td colspan="3"><img src="http://static.woyo.com/woyo/m110214/images/B8_01.jpg" width="750" height="130" alt=""></td></tr><tr><td colspan="3"><img src="http://static.woyo.com/woyo/m110214/images/B8_02.jpg" width="750" height="161" alt=""></td></tr><tr><td colspan="3"><img src="http://static.woyo.com/woyo/m110214/images/B8_03.jpg" width="750" height="137" alt=""></td></tr><tr><td rowspan="2"><img src="http://static.woyo.com/woyo/m110214/images/B8_04.jpg" width="91" height="172" alt=""></td><td><a href="http://www.woyo.com/about/business_cooperation/" target="_blank"><img src="http://static.woyo.com/woyo/m110214/images/B8_05.jpg" width="96" height="90" alt="" border="0"></a></td><td rowspan="2"><img src="http://static.woyo.com/woyo/m110214/images/B8_06.jpg" width="563" height="172" alt=""></td></tr><tr><td><img src="http://static.woyo.com/woyo/m110214/images/B8_07.jpg" width="96" height="82" alt=""></td></tr></table><!-- End ImageReady Slices --></body></html>',
'<html><head><title>电商第二平台我友商城为您带来元宵节的祝福</title><meta http-equiv="Content-Type" content="text/html; charset=gb2312"></head><body bgcolor="#FFFFFF" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0"><!-- ImageReady Slices (B9.jpg) --><table id="Table_01" width="750" height="600" border="0" cellpadding="0" cellspacing="0" align="center"><tr><td colspan="3"><img src="http://static.woyo.com/woyo/m110214/images/B9_01.jpg" width="750" height="179" alt=""></td></tr><tr><td colspan="3"><img src="http://static.woyo.com/woyo/m110214/images/B9_02.jpg" width="750" height="184" alt=""></td></tr><tr><td colspan="3"><img src="http://static.woyo.com/woyo/m110214/images/B9_03.jpg" width="750" height="147" alt=""></td></tr><tr><td rowspan="2"><img src="http://static.woyo.com/woyo/m110214/images/B9_04.jpg" width="334" height="90" alt=""></td><td><a href="http://www.woyo.com/about/business_cooperation/" target="_blank"><img src="http://static.woyo.com/woyo/m110214/images/B9_05.jpg" width="125" height="48" alt="" border="0"></a></td><td rowspan="2"><img src="http://static.woyo.com/woyo/m110214/images/B9_06.jpg" width="291" height="90" alt=""></td></tr><tr><td><img src="http://static.woyo.com/woyo/m110214/images/B9_07.jpg" width="125" height="42" alt=""></td></tr></table><!-- End ImageReady Slices --></body></html>',
'<html><head><title>电商第二平台我友商城为您带来元宵节的祝福</title><meta http-equiv="Content-Type" content="text/html; charset=gb2312"></head><body bgcolor="#FFFFFF" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0"><!-- ImageReady Slices (B10.jpg) --><table id="Table_01" width="750" height="600" border="0" cellpadding="0" cellspacing="0" align="center"><tr><td colspan="3"><img src="http://static.woyo.com/woyo/m110214/images/B10_01.jpg" width="750" height="175" alt=""></td></tr><tr><td colspan="3"><img src="http://static.woyo.com/woyo/m110214/images/B10_02.jpg" width="750" height="198" alt=""></td></tr><tr><td colspan="3"><img src="http://static.woyo.com/woyo/m110214/images/B10_03.jpg" width="750" height="113" alt=""></td></tr><tr><td rowspan="2"><img src="http://static.woyo.com/woyo/m110214/images/B10_04.jpg" width="325" height="114" alt=""></td><td><a href="http://www.woyo.com/about/business_cooperation/" target="_blank"><img src="http://static.woyo.com/woyo/m110214/images/B10_05.jpg" width="128" height="53" alt="" border="0"></a></td><td rowspan="2"><img src="http://static.woyo.com/woyo/m110214/images/B10_06.jpg" width="297" height="114" alt=""></td></tr><tr><td><img src="http://static.woyo.com/woyo/m110214/images/B10_07.jpg" width="128" height="61" alt=""></td></tr></table><!-- End ImageReady Slices --></body></html>',
'<html><head><title>电商第二平台我友商城为您带来元宵节的祝福</title><meta http-equiv="Content-Type" content="text/html; charset=gb2312"></head><body bgcolor="#FFFFFF" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0"><!-- ImageReady Slices (B11.jpg) --><table id="Table_01" width="700" height="650" border="0" cellpadding="0" cellspacing="0" align="center"><tr><td colspan="3"><img src="http://static.woyo.com/woyo/m110214/images/B11_01.jpg" width="700" height="94" alt=""></td></tr><tr><td colspan="3"><img src="http://static.woyo.com/woyo/m110214/images/B11_02.jpg" width="700" height="156" alt=""></td></tr><tr><td colspan="3"><img src="http://static.woyo.com/woyo/m110214/images/B11_03.jpg" width="700" height="147" alt=""></td></tr><tr><td colspan="3"><img src="http://static.woyo.com/woyo/m110214/images/B11_04.jpg" width="700" height="112" alt=""></td></tr><tr><td rowspan="2"><img src="http://static.woyo.com/woyo/m110214/images/B11_05.jpg" width="57" height="141" alt=""></td><td><a href="http://www.woyo.com/about/business_cooperation/" target="_blank"><img src="http://static.woyo.com/woyo/m110214/images/B11_06.jpg" width="132" height="67" alt="" border="0"></a></td><td rowspan="2"><img src="http://static.woyo.com/woyo/m110214/images/B11_07.jpg" width="511" height="141" alt=""></td></tr><tr><td><img src="http://static.woyo.com/woyo/m110214/images/B11_08.jpg" width="132" height="74" alt=""></td></tr></table><!-- End ImageReady Slices --></body></html>',
'<html><head><title>电商第二平台我友商城为您带来元宵节的祝福</title><meta http-equiv="Content-Type" content="text/html; charset=gb2312"></head><body bgcolor="#FFFFFF" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0"><!-- ImageReady Slices (B12.jpg) --><table id="Table_01" width="700" height="650" border="0" cellpadding="0" cellspacing="0" align="center"><tr><td colspan="3"><img src="http://static.woyo.com/woyo/m110214/images/B12_01.jpg" width="700" height="137" alt=""></td></tr><tr><td colspan="3"><img src="http://static.woyo.com/woyo/m110214/images/B12_02.jpg" width="700" height="147" alt=""></td></tr><tr><td colspan="3"><img src="http://static.woyo.com/woyo/m110214/images/B12_03.jpg" width="700" height="179" alt=""></td></tr><tr><td rowspan="2"><img src="http://static.woyo.com/woyo/m110214/images/B12_04.jpg" width="496" height="187" alt=""></td><td><a href="http://www.woyo.com/about/business_cooperation/" target="_blank"><img src="http://static.woyo.com/woyo/m110214/images/B12_05.jpg" width="136" height="53" alt="" border="0"></a></td><td rowspan="2"><img src="http://static.woyo.com/woyo/m110214/images/B12_06.jpg" width="68" height="187" alt=""></td></tr><tr><td><img src="http://static.woyo.com/woyo/m110214/images/B12_07.jpg" width="136" height="134" alt=""></td></tr></table><!-- End ImageReady Slices --></body></html>'

);
my @mail_subjects = (
    '新年快乐，我友商城邀您进入电商运营新时代！',
    '节日快乐，电商第二平台我友商城诚邀您的入驻！',
'新年新气象，我友商城邀您进入低成本、多渠道、多平台的电商运营时代！',
    '新年新气象，我友商城助您新年锦上添花！',
'掌柜们新年快乐！我友商城真诚邀您进入全新电商时代！',
'大掌柜的，新年快乐！我友商城邀您进入电商运营新时代！',
'新的一年开启新的希望，我友商城真诚邀您进入电商新时代！',
'摆脱单一平台运营，更低成本、更多机遇，我友商城诚邀您进入电商新时代！',
'新年快乐，欢迎入驻我友网电商平台，享受更低成本更多机遇！',
    '元宵节快乐，我友商城邀您进入电商运营新时代！',
    '新春快乐，电商第二平台我友商城诚邀您的入驻！',
    '我友商城邀您的入驻，开启电商运营新时代！'
);
open( MAIL_LIST, '<',  'mail_list.txt' ) or die $!;
open( MAIL_LOG,  '>>', 'mail_logs.txt' ) or die $!;

while (<MAIL_LIST>) {
    chomp;
    my ( $mail_name, $mail_domain ) = split( /@/, $_ );
    my $mail_subject = $mail_subjects[ int( rand( $#mail_subjects + 1 ) ) ];
    my $mail_content = $mail_contents[ int( rand( $#mail_contents + 1 ) ) ];
    my $tt           = time();
    my $host_id      = hostname();
    $mail_content =
        $mail_content
      . "<img src=\"http://ad1.woyo.com/s.gif?mc=2011021601" . '&'
      . "ts=$tt" . '&'
      . "host_id=$host_id" . '&'
      . "mail=$mail_name" . '@'
      . "$mail_domain\" />";

    my $subject_gb2312_base64 =
      encode_base64( encode( "gb2312", $mail_subject ) );
    $subject_gb2312_base64 =~ s/\s+//g;
    my $content_gb2312_base64 =
      encode_base64( encode( "gb2312", $mail_content ) );
    my $rand_int = int( rand(100001) ) + 50000;
    my @ds       = (
        'sina.com',  'yahoo.com.cn', '21cn.com',     'tom.com',
        'msn.com',   'live.cn',      'vip.sina.com', '188.com',
        'yahoo.com', 'yahoo.cn'
    );
    my $ds1  = $ds[ int( rand( $#ds + 1 ) ) ];
    my $from = $rand_int . '@' . $ds1;
    my $mail = $mail_name . '@' . $mail_domain;

    my $cmd =
"echo -e \"Reply-To: $from\nFrom: $from\nTo: $mail\nContent-Type: text/html;charset=gb2312\nContent-Transfer-Encoding:base64\nSubject: =?gb2312?B?$subject_gb2312_base64?=\nContent-Type: text/html; charset=\"gb2312\"\n\n$content_gb2312_base64\n\n\" | sendmail  -f$from -F $from $mail";
    system($cmd);
    print MAIL_LOG $mail, "\n";
    sleep(4);

}
close(MAIL_LOG);
close(MAIL_LIST);

